### ISSUE TITLE
Add NEEO as remote

### ISSUE THREAD

**Issue by jaburges** [vinteo/hass-neeo#1]
Hey there,
nice job! not sure how to raise a question, or start an effort. 

I'm not a dev (but a tinkerer) and happy to help where possible. Wondered if there was a way to replicate the harmony remote style. I started looking at harmony.py in the HA GitHub, but don't know enough code to try a merge.

Do you think you would be up for a go (a few folks on the HA side i imagine would chip in to make an official component)?

Keen to hear your thoughts on how to implement? 

Possibly import as a remote? So would be remote.neeo (rather than switches)
Then you could 
```
service: remote.send_command
entity_id: remote.neeo
  data: 
    room: 1231214
    device: 1231231
    key: 123123
```

or 

```
service: remote.receipe_turn_on
entity_id: remote.neeo
```

really appreciate you sharing too!
